forge 'bx-builder.lunetix.org/puppet-modules'

mod 'buildhost', :git => 'git@bx-builder.lunetix.org:profile-buildhost'
mod 'dockerhost', :git => 'git@bx-builder.lunetix.org:profile-dockerhost'
mod 'git', :git => 'git@bx-builder.lunetix.org:module-git'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/postgresql', '4.6.1'
mod 'puppetlabs/concat'
mod 'puppetlabs/apache'
mod 'rtyler/jenkins', '1.6.1'
mod 'camptocamp/archive'
mod 'nanliu/staging'
mod 'puppetlabs/java'
